### ISSUE TITLE
[Bug]: Error when installing on Win11, 3.12.1, because of pysam not supporting PEP 517 builds.

### ISSUE THREAD

**Issue by htmonkey** [sdsc-ordes/modos-api#112]
### What happened?

I tried several times to install via pip and poetry in clean venvs, on 3.10 and 3.12, but it always fails because of pysam-0.22.1 and PEP517.
PS: I can install it on Ubuntu.
PS2: pip, wheel, setuptools, etc are all updated.

This is the cleanest error log:

PS D:\SW\modo-test> poetry add modos
Using version ^0.2.2 for modos

Updating dependencies
Resolving dependencies... (2.2s)

Package operations: 67 installs, 0 updates, 0 removals

  - Installing typing-extensions (4.12.2)
  - Installing annotated-types (0.7.0)
  - Installing attrs (24.2.0)
  - Installing colorama (0.4.6)
  - Installing iniconfig (2.0.0)
  - Installing packaging (24.2)
  - Installing pluggy (1.5.0)
  - Installing pydantic-core (2.27.1)
  - Installing rpds-py (0.21.0)
  - Installing sortedcontainers (2.4.0)
  - Installing certifi (2024.8.30)
  - Installing charset-normalizer (3.4.0)
  - Installing frozenlist (1.5.0)
  - Installing idna (3.10)
  - Installing multidict (6.1.0)
  - Installing propcache (0.2.0)
  - Installing pydantic (2.10.2)
  - Installing pytest (8.3.3)
  - Installing pytrie (0.4.0)
  - Installing referencing (0.35.1)
  - Installing six (1.16.0)
  - Installing urllib3 (2.2.3)
  - Installing aiohappyeyeballs (2.4.3)
  - Installing aiosignal (1.3.1)
  - Installing click (8.1.7)
  - Installing curies (0.9.0)
  - Installing hbreader (0.9.1)
  - Installing isodate (0.6.1)
  - Installing jmespath (1.0.1)
  - Installing jsonschema-specifications (2024.10.1)
  - Installing pyparsing (3.2.0)
  - Installing pytest-logging (2015.11.4)
  - Installing python-dateutil (2.9.0.post0)
  - Installing pyyaml (6.0.2)
  - Installing requests (2.32.3)
  - Installing wrapt (1.17.0)
  - Installing yarl (1.18.0)
  - Installing aiohttp (3.11.8)
  - Installing aioitertools (0.12.0)
  - Installing botocore (1.35.36)
  - Installing cachetools (5.5.0)
  - Installing deprecated (1.2.15)
  - Installing frozendict (2.4.6)
  - Installing json-flattener (0.1.9)
  - Installing jsonasobj2 (1.0.4)
  - Installing jsonschema (4.23.0)
  - Installing lxml (5.3.0)
  - Installing numpy (2.1.3)
  - Installing prefixcommons (0.1.12)
  - Installing prefixmaps (0.2.6)
  - Installing rdflib (6.3.2)
  - Installing aiobotocore (2.15.2)
  - Installing asciitree (0.3.3)
  - Installing fasteners (0.19)
  - Installing fsspec (2024.10.0)
  - Installing lazy-object-proxy (1.10.0)
  - Installing linkml-runtime (1.8.3)
  - Installing marshmallow (3.23.1)
  - Installing numcodecs (0.14.1)
  - Installing pyld (2.0.4)
  - Installing calamus (0.4.2)
  - Installing modos-schema (0.1.0)
  - Installing pysam (0.22.1): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel

  # pysam: cython is available - using cythonize if necessary
  # pysam: htslib mode is shared
  # pysam: HTSLIB_CONFIGURE_OPTIONS=None
  '.' is not recognized as an internal or external command,
  operable program or batch file.
  '.' is not recognized as an internal or external command,
  operable program or batch file.
  # pysam: htslib configure options: None
  Traceback (most recent call last):
    File "C:\Users\nzamboni\pipx\venvs\poetry\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 373, in <module>
      main()
    File "C:\Users\nzamboni\pipx\venvs\poetry\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 357, in main
      json_out["return_val"] = hook(**hook_input["kwargs"])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\nzamboni\pipx\venvs\poetry\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 134, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\nzamboni\AppData\Local\Temp\tmpve2z1hdi\.venv\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=[])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\nzamboni\AppData\Local\Temp\tmpve2z1hdi\.venv\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
      self.run_setup()
    File "C:\Users\nzamboni\AppData\Local\Temp\tmpve2z1hdi\.venv\Lib\site-packages\setuptools\build_meta.py", line 522, in run_setup
      super().run_setup(setup_script=setup_script)
    File "C:\Users\nzamboni\AppData\Local\Temp\tmpve2z1hdi\.venv\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
      exec(code, locals())
    File "<string>", line 437, in <module>
    File "<string>", line 81, in run_make_print_config
    File "D:\libs\Python312\Lib\subprocess.py", line 466, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "D:\libs\Python312\Lib\subprocess.py", line 548, in run
      with Popen(*popenargs, **kwargs) as process:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "D:\libs\Python312\Lib\subprocess.py", line 1026, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "D:\libs\Python312\Lib\subprocess.py", line 1538, in _execute_child
      hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  FileNotFoundError: [WinError 2] The system cannot find the file specified

  at ~\pipx\venvs\poetry\Lib\site-packages\poetry\installation\chef.py:164 in _prepare
      160│
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│
      163│             if error is not None:
    → 164│                 raise error from None
      165│
      166│             return path
      167│
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with pysam (0.22.1) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "pysam (==0.22.1)"'.

  - Installing s3fs (2024.10.0)
  - Installing typer (0.9.4)
  - Installing zarr (2.18.3)
PS D:\SW\modo-test> pip wheel --no-cache-dir --use-pep517 "pysam (==0.22.1)
>> "
Collecting pysam==0.22.1
  Downloading pysam-0.22.1.tar.gz (4.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 14.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      # pysam: cython is available - using cythonize if necessary
      # pysam: htslib mode is shared
      # pysam: HTSLIB_CONFIGURE_OPTIONS=None
      '.' is not recognized as an internal or external command,
      operable program or batch file.
      '.' is not recognized as an internal or external command,
      operable program or batch file.
      # pysam: htslib configure options: None
      Traceback (most recent call last):
        File "D:\libs\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\libs\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\libs\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\nzamboni\AppData\Local\Temp\pip-build-env-vxmt1xno\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\nzamboni\AppData\Local\Temp\pip-build-env-vxmt1xno\overlay\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "C:\Users\nzamboni\AppData\Local\Temp\pip-build-env-vxmt1xno\overlay\Lib\site-packages\setuptools\build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\nzamboni\AppData\Local\Temp\pip-build-env-vxmt1xno\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 437, in <module>
        File "<string>", line 81, in run_make_print_config
        File "D:\libs\Python312\Lib\subprocess.py", line 466, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\libs\Python312\Lib\subprocess.py", line 548, in run
          with Popen(*popenargs, **kwargs) as process:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\libs\Python312\Lib\subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "D:\libs\Python312\Lib\subprocess.py", line 1538, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

### What system are you using?

Microsoft Windows

**Comment by cmdoret** [comment]
It seems that pysam indeed does not work on windows, however it should work using WSL (see https://github.com/pysam-developers/pysam/issues/575).

Is using WSL a major issue? If so we can try something else, but AFAIK pysam is the only implementation of CRAM parsing / manipulation in python.

**Comment by htmonkey** [comment]
This is a bummer. The whole idea behind MODO is to enable users to import and compute in their preferred environment. WSL is a poor compromise (no graphics for data analysis, speed, etc). For now, I'll use the channel via Jupyter for testing.
